apiVersion: v1
entries:
  farsight-collector-colo:
  - apiVersion: v1
    appVersion: "1.1"
    created: "2023-07-14T14:59:38.459174-07:00"
    description: Farsight Colo app
    digest: 8fe4062f17c0a2f3a59adbf6b9ba3fb5dbd999e1df9d81b71f09f005b2254ab5
    name: farsight-collector-colo
    urls:
    - farsight-collector-colo-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v1
    appVersion: "1.0"
    created: "2023-07-14T14:59:38.4588-07:00"
    description: A Helm chart for Kubernetes
    digest: 5f26c0cb335f23b14beb2d6024cd51010e97f598af65b1e2e0db822e3e8057dc
    name: farsight-collector-colo
    urls:
    - farsight-collector-colo-1.0.5.tgz
    version: 1.0.5
  - apiVersion: v1
    appVersion: "1.0"
    created: "2023-07-14T14:59:38.458069-07:00"
    description: A Helm chart for Kubernetes
    digest: e46729b1acd27ac3a09c56c53029133d2149933cb4952c3ccacfe8747183c632
    name: farsight-collector-colo
    urls:
    - farsight-collector-colo-1.0.4.tgz
    version: 1.0.4
  - apiVersion: v1
    appVersion: "1.0"
    created: "2023-07-14T14:59:38.457473-07:00"
    description: A Helm chart for Kubernetes
    digest: 1f36d158f893cfa14ae6a9a4692a152ae204d3f987629422dd773ffca9c61230
    name: farsight-collector-colo
    urls:
    - farsight-collector-colo-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v1
    appVersion: "1.0"
    created: "2023-07-14T14:59:38.456878-07:00"
    description: A Helm chart for Kubernetes
    digest: c5e5397415e34cc9b23200c652f09fdb741c8444f0f968f05eb2175cea546708
    name: farsight-collector-colo
    urls:
    - farsight-collector-colo-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v1
    appVersion: "1.0"
    created: "2023-07-14T14:59:38.456183-07:00"
    description: A Helm chart for Kubernetes
    digest: ce65249f18d3d6c9e9e7a6b0f6170f815d9e9d3758e463e279e798442c66404e
    name: farsight-collector-colo
    urls:
    - farsight-collector-colo-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v1
    appVersion: "1.0"
    created: "2023-07-14T14:59:38.455626-07:00"
    description: A Helm chart for Kubernetes
    digest: 8b59d6d2b4b913056318e5474cb070ed58bbaf8c84c9adde16725903aff3669a
    name: farsight-collector-colo
    urls:
    - farsight-collector-colo-1.0.0.tgz
    version: 1.0.0
generated: "2023-07-14T14:59:38.45474-07:00"
